---
title: "Experience"
author: "Henry Stoddard"
date: "10/31/2020"
output: html_document
---
# This is information on my academic and professional experiences

## Education
I graduated from Portland High School in 2015, then from Tulane University in 2019, and now I attend Columbia University Mailman School of Public Health (expected graduation date May 2021).
I also studied abroad in South Africa!

## Work
I have worked in a variety of public health research and consulting positions. In my undergraduate degree, I worked at the Lousiana Department of Health and conducted research with a professor studying qualitative data from interviews with people who use drugs.

Since then, I have worked for MaineHealth Operational Excellence, I was a TA for a summer class at Columbia, and I completed research at the Columbia Center for Outcomes Research and Decision Analysis regarding Familial Hypercholesterolemia.

## Volunteer
As an undergraduate student, I frequently volunteered as an EMT through New Orleans EMS and Tulane EMS. Additionally, I have been working as a volunteer intern for the NYC Department of Health since this past summer.
